### ISSUE TITLE
Issue with main.py (& barcode_scanner.py)

### ISSUE THREAD

**Issue by thebotmakes** [sbcshop/Pi-Barcode-HAT#1]
I'm trying to run the main.py file with the barcode scanner hat in place.  I've scanned the two barcodes before starting, and moved all the files from application to the parent Pi-Barcode-HAT folder.  When I try and run main.py (or barcode_scanner.py) I get the following traceback:

Traceback (most recent call last):
  File "/home/pi/Pi-Barcode-HAT/main.py", line 9, in <module>
    from lib import lcd1_14driver
  File "/home/pi/Pi-Barcode-HAT/lib/lcd1_14driver.py", line 3, in <module>
    from . import lcd_config
  File "/home/pi/Pi-Barcode-HAT/lib/lcd_config.py", line 5, in <module>
    class RaspberryPi:
  File "/home/pi/Pi-Barcode-HAT/lib/lcd_config.py", line 6, in RaspberryPi
    def __init__(self,spi=spidev.SpiDev(0,0),spi_freq=40000000,rst = 27,dc = 25,bl = 18,bl_freq=1000,i2c=None,i2c_freq=100000):
FileNotFoundError: [Errno 2] No such file or directory

**Comment by sbcshop1** [comment]
This issue arises due to SPI. kindly enable the SPI first, for this to cmd then type "sudo raspi-config"  then go to ->interface option ->  SPI - YES

**Comment by thebotmakes** [comment]
OK thanks - also had to allow the serial interface through raspi-config as had a further error but all working now.  Might be worth adding those steps to the readme?
